version: "3"

services:
  backend:
    build: ./promo-portal-back
    volumes:
      - ./promo-portal-back/:/backend # maps host diretory to internal container directory
    working_dir: /promo-portal-back/
    command: sh entrypoint.sh
  frontend:
    build: ./promo-portal
    working_dir: /promo-portal/
    volumes:
      - ./promo-portal/:/frontend
    command: bash -c "yarn && yarn dev"
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./promo-portal/build:/var/www/frontend
    depends_on:
      - backend
